package com.TimothyJmartKD.jmart_android.model;

public enum ProductCategory {
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, COSMETICS,
    HEALTHCARE, FURNITURE, JEWELERY, TOYS, FNB, STATIONERY, SPORTS, AUTOMOTIVE,
    PETCARE,ART_CRAFT,CARPENTRY,MISCELLANEOUS, PROPERTY, TRAVEL, WEDDING;
}
